application:  zaqwsxedce
version: beta-7
runtime: python
api_version: 1

builtins:
- remote_api: on

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /.*
  script: main.py
